name: CI/CD Backend Express.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.9.0

      - name: Install dependencies
        run: npm install

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # IP atau domain server Anda
          username: ${{ secrets.SSH_USERNAME }} # Username SSH (biasanya 'root' atau 'ubuntu')
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Private key SSH
          script: |
            export PATH=$PATH:/home/crooud/.nvm/versions/node/v22.9.0/bin
            rsync -avz --delete ./ crooud@103.49.239.214:/var/www/backend
            cd /var/www/backend
            npm install --production
            pm2 restart titaniumprinting
